[project]
name = "all-about-fastapi"
version = "0.1.0"
description = "This is to work with FastAPI to undertand it's capabilities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]"
]
